name: approve-pull-request

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * 1,2,3,4,5 # every M,T,W,Th,F at 8pm UTC (4pm EST) 
      
jobs:
  approvePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find issue
        run: | 
          echo "$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')"
          echo "ISSUE=$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')" >> $GITHUB_ENV

      - name: Find pull request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{ env.ISSUE }}
      
      - name: Comment on pull request
        id: compr
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT2 }} # billlumbergh-initech
          pr_number: ${{ steps.find-pull-request.outputs.number }}
          message: |
            Well... yeah.
          
      - name: Approve pull request
        id: apr
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.PAT2 }} # billlumbergh-initech
          number: ${{ steps.find-pull-request.outputs.number }}
