name: approve-pull-request

on:
  workflow_dispatch: 
      
jobs:
  approvePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download pull request
        uses: actions/download-artifact@v3
        with:
          name: pull-request

      - shell: bash
        id: retrieve-pull-request
        run: |
          value=`cat pull-request.txt`
          echo "::set-output name=pull-request::$value"
      
      - name: Comment on pull request
        id: compr
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
          pr_number: ${{ steps.retrieve-pull-request.outputs.pull-request }}
          message: |
            Well... yeah.
          
      - name: Approve pull request
        id: apr
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.PAT2 }}
          number: ${{ steps.retrieve-pull-request.outputs.pull-request }}
