name: create-issue

on:
  workflow_dispatch: 
      
jobs:
  createIssue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Jira
        id: jira-login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Create
        id: jira-create
        uses: atlassian/gajira-create@v3
        with:
          project: Y2K
          issuetype: Task
          summary: Fix y2k
          description: Created automatically via GitHub Actions
      
      - name: Create a branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.jira-create.outputs.issue }}
      
      - name: Get branch
        run: echo "BRANCH=$(git for-each-ref --count=2 --sort=-committerdate refs/heads/ --format='%(refname:short)' | grep -v "main")" >> $GITHUB_ENV

      # - name: Save issue
      #   run: echo "${{ steps.jira-create.outputs.issue }}" > ./.github/dist/issue.txt

      # - name: Commit issue
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     message: Update issue
