name: create-commit

on:
  workflow_dispatch: 
      
jobs:
  createCommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetches all branches
      
      - name: Get branch
        run: | 
          echo "$(git for-each-ref --count=2 --sort=-committerdate refs/heads/ | grep -v "main")"
          echo "BRANCH=$(git for-each-ref --count=2 --sort=-committerdate refs/heads/ | grep -v "main")" >> $GITHUB_ENV

      - name: Make changes
        run: date +%s > report.txt

      - name: Commit and push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
