name: create-issue

on:
  schedule: 
    - cron: 0 9 * * 1,2,3,4,5 # every M,T,W,Th,F at 9am UTC (5am EST)
      
jobs:
  createIssue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Jira
        id: jira-login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Create
        id: jira-create
        uses: atlassian/gajira-create@v3
        with:
          project: Y2K
          issuetype: Task
          summary: Fix y2k
          description: Created automatically via GitHub Actions
      
      - name: Create a branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT3 }} # petergibbons22
        with:
          branch: ${{ steps.jira-create.outputs.issue }}
