name: create-commit

on:
  workflow_dispatch:
  schedule: 
    - cron: 30 22 * * * # every day at 10:30pm UTC (6:30pm EST)
      
jobs:
  createCommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetches all branches
      
      - name: Get branch
        run: | 
          echo "$(git ls-remote --heads origin | grep "Y2K" | head -1 | sed 's?.*refs/heads/??')"
          echo "BRANCH=$(git ls-remote --heads origin | grep "Y2K" | head -1 | sed 's?.*refs/heads/??')" >> $GITHUB_ENV

      - name: Make changes
        run: date +%s > report.txt

      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "update date"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT3 }} # petergibbons2
          branch: ${{ env.BRANCH }}
          force: true
