name: create-commit

on:
  workflow_dispatch: 
      
jobs:
  createCommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetches all branches
      
      - name: Get branch
        run: | 
          echo "$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')"
          echo "BRANCH=$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')" >> $GITHUB_ENV

      - name: Make changes
        run: date +%s > report.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "update date"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
