name: create-pull-request

on:
  workflow_dispatch: 
      
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Make changes
        run: date +%s > report.txt

      - shell: bash
        id: retrieve-issue
        run: |
          value=`cat issue.txt`
          echo "::set-output name=issue::$value"

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Fix y2k (${{ steps.retrieve-issue.outputs.issue }})
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: fix-${{ steps.retrieve-issue.outputs.issue }}
          delete-branch: true
          title: Fix y2k (${{ steps.retrieve-issue.outputs.issue }})
          body: |
            - Updated with *today's* date
          labels: |
            bug
          reviewers: billlumbergh-initech
          draft: false
      
      - shell: bash
        run: echo "${{ steps.cpr.outputs.pull-request-number }}" > ./.github/dist/pull-request.txt
      
      - name: Upload pull request
        uses: actions/upload-artifact@v3
        with:
          name: pull-request
          path: ./.github/dist/pull-request.txt
