name: create-pull-request

on:
  schedule:
    - cron: 30 14 * * 1,2,3,4,5 # every M,T,W,Th,F at 2:30pm UTC (10:30am EST) 
      
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get issue
        run: | 
          echo "$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')"
          echo "ISSUE=$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')" >> $GITHUB_ENV

      - name: Make changes
        run: date +%s > report.txt

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Fix y2k (${{ env.ISSUE }})
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.ISSUE }}
          delete-branch: true
          title: Fix y2k (${{ env.ISSUE }})
          body: |
            - Updated with *today's* date
          labels: |
            bug
          reviewers: billlumbergh-initech
          draft: false
