name: fast-pull-request

on:
  workflow_dispatch:
  schedule:
    - cron: 15 22 * * 1,2,3,4,5 # every M,T,W,Th,F at 10:15pm UTC (6:15pm EST) 
      
jobs:
  fastPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Jira
        id: jira-login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Create issue
        id: jira-create
        uses: atlassian/gajira-create@v3
        with:
          project: Y2K
          issuetype: Bug
          summary: Bug fix
          description: Created automatically via GitHub Actions
      
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT3 }} # petergibbons22
        with:
          branch: ${{ steps.jira-create.outputs.issue }}

      - name: Make changes
        run: date +%s > report.txt

      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "Bug fix"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT3 }} # petergibbons22
          branch: ${{ steps.jira-create.outputs.issue }}
          force: true
  
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.PAT3 }} # petergibbons22
          commit-message: Bug fix (${{ steps.jira-create.outputs.issue }})
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ steps.jira-create.outputs.issue }}
          delete-branch: true
          title: Bug fix (${{ steps.jira-create.outputs.issue }})
          body: |
            - Fix bug
          labels: |
            bug
          reviewers: billlumbergh-initech
          draft: false
          
      - name: Approve pull request
        id: apr
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.PAT2 }} # billlumbergh-initech
          number: ${{ steps.cpr.outputs.pull-request-number }}
        
      - name: Merge pull request
        id: mpr
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT3 }}  # petergibbons22
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash
