name: merge-pull-request

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 1,2,3,4,5 # every M,T,W,Th,F at 9pm UTC (5pm EST) 
      
jobs:
  mergePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find issue
        run: | 
          echo "$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')"
          echo "ISSUE=$(git ls-remote --heads origin | grep -v "main" | head -1 | sed 's?.*refs/heads/??')" >> $GITHUB_ENV

      - name: Find pull request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{ env.ISSUE }}
        
      - name: Merge pull request
        id: mpr
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT3 }}  # petergibbons2
          number: ${{ steps.find-pull-request.outputs.number }}
          method: squash
