name: merge-pull-request

on:
  workflow_dispatch: 
      
jobs:
  mergePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download pull request
        uses: actions/download-artifact@v3
        with:
          name: pull-request

      - shell: bash
        id: retrieve-pull-request
        run: |
          value=`cat pull-request.txt`
          echo "::set-output name=pull-request::$value"
        
      - name: Merge pull request
        id: mpr
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ steps.retrieve-pull-request.outputs.pull-request }}
          method: squash
